language: python
sudo: false
cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - secure: "HNlbjIcrNwj8/oUHbhWYhUmG1AH/iZwJFSnUiYZVOrQ8NfI4veR0AqHzXJYIK4npsW6yAVpQ1iz6BR/lxMiEgtLwSqNhzXeMNCM/u7FhSOr3wkNHURDhCecyPL1jGd1DKm9p8OWSPoaTOHxFjSbEGVPMWXh8uln8QKwbsJNMqgE="
    - secure: "OnrfYA8v2vemdxouNoB6AOuFGWN2HHSaRaOdpGS4CqERzHoHPz0BMWruzh0d1bfGAoxk+PrbF3t2aWAj4a3X0rQSWSulJ5OF5DP2Nd+HV+0gU+pMo4ze95DOJT5EX1aq3u9CUJ7XdkNMqHwCMpGQOQ50hDXVHA9+vidxUP6nZIc="
  matrix:
    - GDALVERSION="1.9.2"
    - GDALVERSION="1.10.0"  # doesn't exist but path/lib will fall back to system
    - GDALVERSION="1.11.4"
    - GDALVERSION="2.0.2"
    - GDALVERSION="2.1.0"
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libproj-dev
    - libhdf5-serial-dev
    - libpng-dev
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran
python:
  - "2.7"
  - "3.4"
before_install:
  - pip install -U pip
  - pip install wheel
  - . ./scripts/travis_gdal_install.sh
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
install:
  - "if [ $(gdal-config --version) == \"$GDALVERSION\" ]; then echo \"Using gdal $GDALVERSION\"; else echo \"NOT using gdal $GDALVERSION as expected; aborting\"; exit 1; fi"
  - "pip wheel -r requirements-dev.txt"
  - "pip install -r requirements-dev.txt"
  - "pip install --upgrade --force-reinstall --global-option=build_ext --global-option='-I$GDALINST/gdal-$GDALVERSION/include' --global-option='-L$GDALINST/gdal-$GDALVERSION/lib' --global-option='-R$GDALINST/gdal-$GDALVERSION/lib' -e ."
  - "pip install coveralls>=1.1"
  - "pip install -e .[test]"
  - "rio --version"
  - "rio --gdal-version"
script:
  - py.test --cov rasterio --cov-report term-missing
after_success:
  - coveralls || echo "!! intermittent coveralls failure"
