language: python
sudo: false
cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
  matrix:
    - GDALVERSION="1.9.2"
    - GDALVERSION="1.10.0"  # doesn't exist but path/lib will fall back to system
    - GDALVERSION="1.11.4"
    - GDALVERSION="2.0.2"
    - GDALVERSION="2.1.0"
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libproj-dev
    - libhdf5-serial-dev
    - libpng-dev
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran
python:
  - "2.7"
  # - "3.3"   # disabling python3.3 for now
  - "3.4"
before_install:
  - pip install -U pip
  - pip install wheel
  - . ./scripts/travis_gdal_install.sh
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
install:
  - "if [ $(gdal-config --version) == \"$GDALVERSION\" ]; then echo \"Using gdal $GDALVERSION\"; else echo \"NOT using gdal $GDALVERSION as expected; aborting\"; exit 1; fi"
  - "pip wheel -r requirements-dev.txt"
  - "pip install -r requirements-dev.txt"
  - "pip install --upgrade --force-reinstall --global-option=build_ext --global-option='-I$GDALINST/gdal-$GDALVERSION/include' --global-option='-L$GDALINST/gdal-$GDALVERSION/lib' --global-option='-R$GDALINST/gdal-$GDALVERSION/lib' -e ."
  - "pip install coveralls>=1.1"
  - "pip install -e ."
script:
  - py.test --cov rasterio --cov-report term-missing
after_success:
  - coveralls
before_deploy:
  - pip wheel --wheel-dir=/tmp/wheelhouse -r requirements-dev.txt
  - pip wheel --wheel-dir=/tmp/wheelhouse -r requirements.txt
  - pip wheel --wheel-dir=/tmp/wheelhouse .
  - tar -C /tmp -czvf rasterio-travis-wheels-$TRAVIS_PYTHON_VERSION.tar.gz wheelhouse
deploy:
  provider: releases
  api_key:
    secure: uP/hy8LRdDnN6XHSLChmKYdW9CdIy8pqvUyXFPgTDY/mlItMUdDNdP95bitzn/rNNXnOkCGsARqzRCLeGI3jB0nEGuAzY6fGWYt2igjfMOhpdDG6o3LcaoP4mITuFfe5/kCQeUb8WB3QK6c2cL7nEEPzoSniqZQ6MsxHIvUW7ts=
  file: rasterio-travis-wheels-$TRAVIS_PYTHON_VERSION.tar.gz
  on:
    tags: true
